In [ ]:
import pandas as pd
import numpy as np

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
train_df = pd.read_csv("/content/drive/MyDrive/Data_Science_Project_Lifecycle/train.csv")        # for training
val_df = pd.read_csv("/content/drive/MyDrive/Data_Science_Project_Lifecycle/validation.csv")    # for tuning
test_df = pd.read_csv("/content/drive/MyDrive/Data_Science_Project_Lifecycle/test.csv")         # final evaluation

In [ ]:
print(y_train.value_counts())

Cancellation
0    27499
Name: count, dtype: int64

In [ ]:
combined_df = pd.concat([train_df, val_df])

In [ ]:
print(combined_df['Cancellation'].value_counts())

Cancellation
0    30248
Name: count, dtype: int64

In [ ]:
print(y_train.value_counts())
print(y_val.value_counts())

Cancellation
0    24198
Name: count, dtype: int64
Cancellation
0    6050
Name: count, dtype: int64

In [ ]:
print(combined_df['Cancellation'].unique())

[0]

In [ ]:
print(val_df['Cancellation'].value_counts())

Cancellation
0    2749
Name: count, dtype: int64

In [ ]:
print(test_df['Cancellation'].value_counts())

Cancellation
0    4318
Name: count, dtype: int64

In [ ]:
print(val_df['Cancellation'].unique())

[0]

In [ ]:
print(train_df.columns)

Index(['Reservation-id', 'Gender', 'Age', 'Ethnicity', 'Educational_Level',
       'Income', 'Country_region', 'Hotel_Type', 'Expected_checkin',
       'Expected_checkout', 'Booking_date', 'Adults', 'Children', 'Babies',
       'Meal_Type', 'Visted_Previously', 'Previous_Cancellations',
       'Deposit_type', 'Booking_channel', 'Required_Car_Parking',
       'Reservation_Status', 'Use_Promotion', 'Discount_Rate', 'Room_Rate',
       'Cancellation', 'Lead_Time'],
      dtype='object')

In [ ]:
print(train_df.head())

   Reservation-id Gender  Age         Ethnicity Educational_Level  \
0        39428300      F   40            Latino              Grad
1        77491756      F   49            Latino        Mid-School
2        73747291      F   42         caucasian              Grad
3        67301739      M   25  African American           College
4        77222321      F   62            Latino       High-School

        Income Country_region      Hotel_Type Expected_checkin  \
0         <25K          North      City Hotel       2015-07-01
1  50K -- 100K           East      City Hotel       2015-07-01
2         <25K           East      City Hotel       2015-07-02
3        >100K          South  Airport Hotels       2015-07-02
4    25K --50K           East          Resort       2015-07-03

  Expected_checkout  ... Previous_Cancellations  Deposit_type  \
0          7/2/2015  ...                     No    No Deposit
1          7/2/2015  ...                     No    Refundable
2          7/6/2015  ...                     No    No Deposit
3          7/3/2015  ...                     No    Refundable
4          7/4/2015  ...                     No    No Deposit

   Booking_channel  Required_Car_Parking Reservation_Status Use_Promotion  \
0           Online                   Yes          Check-Out           Yes
1           Online                   Yes          Check-Out            No
2           Online                   Yes          Check-Out            No
3            Agent                   Yes          Check-Out           Yes
4           Direct                    No          Check-Out           Yes

  Discount_Rate Room_Rate Cancellation Lead_Time
0            10       218            0        41
1             0       185            0        36
2             0       119            0         3
3             5       144            0        12
4            10       242            0        13

[5 rows x 26 columns]

In [ ]:
combined_df = pd.concat([train_df, val_df, test_df], ignore_index=True)

In [ ]:
combined_df['Cancellation'] = combined_df['Reservation_Status'].apply(
    lambda x: 1 if x in ['Cancelled', 'No Show'] else 0
)

In [ ]:
print(combined_df['Cancellation'].value_counts())

Cancellation
0    34566
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X = combined_df[features]
y = combined_df['Cancellation']

X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
X_train = pd.get_dummies(X_train)
X_val = pd.get_dummies(X_val)

# Align columns (very important)
X_train, X_val = X_train.align(X_val, join='left', axis=1, fill_value=0)

In [ ]:
print(combined_df['Reservation_Status'].unique())
print(combined_df['Cancellation'].value_counts())

['Check-Out' 'Canceled' 'No-Show' 'Check-out' 'Check-In' nan]
Cancellation
0    34566
Name: count, dtype: int64

In [ ]:
combined_df['Cancellation'] = combined_df['Reservation_Status'].apply(
    lambda x: 1 if str(x).strip().lower() in ['canceled', 'no-show'] else 0
)

In [ ]:
print(combined_df['Cancellation'].value_counts())

Cancellation
0    27168
1     7398
Name: count, dtype: int64

In [ ]:
print(y_train.value_counts())

Cancellation
0    21734
1     5918
Name: count, dtype: int64

In [ ]:
lr.fit(X_train, y_train)

ValueError: could not convert string to float: 'Airport Hotels'

In [ ]:
# Convert categorical variables to numbers
X_train = pd.get_dummies(X_train)
X_val = pd.get_dummies(X_val)

# Align columns (CRUCIAL)
X_train, X_val = X_train.align(X_val, join='left', axis=1, fill_value=0)

In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

# Predictions
y_pred = lr.predict(X_val)

# Accuracy
print("Accuracy:", accuracy_score(y_val, y_pred))

# Detailed metrics
print(classification_report(y_val, y_pred))

Accuracy: 0.7859415678333815
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      5434
           1       0.00      0.00      0.00      1480

    accuracy                           0.79      6914
   macro avg       0.39      0.50      0.44      6914
weighted avg       0.62      0.79      0.69      6914

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Decision Tree
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

# Random Forest
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
# Train Decision Tree
dt.fit(X_train, y_train)

# Predict
y_pred_dt = dt.predict(X_val)

# Evaluate
from sklearn.metrics import classification_report, accuracy_score

print("Decision Tree Accuracy:", accuracy_score(y_val, y_pred_dt))
print(classification_report(y_val, y_pred_dt))

Decision Tree Accuracy: 0.6481052936071738
              precision    recall  f1-score   support

           0       0.79      0.75      0.77      5434
           1       0.23      0.26      0.24      1480

    accuracy                           0.65      6914
   macro avg       0.51      0.51      0.51      6914
weighted avg       0.67      0.65      0.66      6914

In [ ]:
rf = RandomForestClassifier(random_state=42, class_weight='balanced')

rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_val)

print("Random Forest Accuracy:", accuracy_score(y_val, y_pred_rf))
print(classification_report(y_val, y_pred_rf))

Random Forest Accuracy: 0.7681515765114261
              precision    recall  f1-score   support

           0       0.79      0.96      0.87      5434
           1       0.27      0.05      0.08      1480

    accuracy                           0.77      6914
   macro avg       0.53      0.51      0.48      6914
weighted avg       0.68      0.77      0.70      6914

In [ ]:
rf = RandomForestClassifier(random_state=42, class_weight='balanced')
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_val)

print("Random Forest Accuracy:", accuracy_score(y_val, y_pred_rf))
print(classification_report(y_val, y_pred_rf))

Random Forest Accuracy: 0.7681515765114261
              precision    recall  f1-score   support

           0       0.79      0.96      0.87      5434
           1       0.27      0.05      0.08      1480

    accuracy                           0.77      6914
   macro avg       0.53      0.51      0.48      6914
weighted avg       0.68      0.77      0.70      6914

In [ ]:
rf = RandomForestClassifier(random_state=42, class_weight='balanced')
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_val)

from sklearn.metrics import classification_report, accuracy_score

print("Random Forest Accuracy:", accuracy_score(y_val, y_pred_rf))
print(classification_report(y_val, y_pred_rf))

Random Forest Accuracy: 0.7681515765114261
              precision    recall  f1-score   support

           0       0.79      0.96      0.87      5434
           1       0.27      0.05      0.08      1480

    accuracy                           0.77      6914
   macro avg       0.53      0.51      0.48      6914
weighted avg       0.68      0.77      0.70      6914

In [ ]:
rf = RandomForestClassifier(random_state=42, class_weight='balanced')
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_val)

print(classification_report(y_val, y_pred_rf))

              precision    recall  f1-score   support

           0       0.79      0.96      0.87      5434
           1       0.27      0.05      0.08      1480

    accuracy                           0.77      6914
   macro avg       0.53      0.51      0.48      6914
weighted avg       0.68      0.77      0.70      6914

In [ ]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Predictions
y_pred_lr = lr.predict(X_val)
y_pred_dt = dt.predict(X_val)
y_pred_rf = rf.predict(X_val)

# Create comparison table
results = pd.DataFrame({
    'Model': ['Logistic Regression', 'Decision Tree', 'Random Forest'],

    'Accuracy': [
        accuracy_score(y_val, y_pred_lr),
        accuracy_score(y_val, y_pred_dt),
        accuracy_score(y_val, y_pred_rf)
    ],

    'Precision (Class 1)': [
        precision_score(y_val, y_pred_lr),
        precision_score(y_val, y_pred_dt),
        precision_score(y_val, y_pred_rf)
    ],

    'Recall (Class 1)': [
        recall_score(y_val, y_pred_lr),
        recall_score(y_val, y_pred_dt),
        recall_score(y_val, y_pred_rf)
    ],

    'F1-Score (Class 1)': [
        f1_score(y_val, y_pred_lr),
        f1_score(y_val, y_pred_dt),
        f1_score(y_val, y_pred_rf)
    ]
})

results

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

,Model,Accuracy,Precision (Class 1),Recall (Class 1),F1-Score (Class 1)
0,Logistic Regression,0.785942,0.000000,0.000000,0.000000
1,Decision Tree,0.648105,0.225360,0.264189,0.243235
2,Random Forest,0.768152,0.271375,0.049324,0.083476

In [ ]:
results.style.format({
    'Accuracy': "{:.2f}",
    'Precision (Class 1)': "{:.2f}",
    'Recall (Class 1)': "{:.2f}",
    'F1-Score (Class 1)': "{:.2f}"
}).background_gradient(cmap='Blues')

In [ ]:
results.sort_values(by='F1-Score (Class 1)', ascending=False)

,Model,Accuracy,Precision (Class 1),Recall (Class 1),F1-Score (Class 1)
1,Decision Tree,0.648105,0.225360,0.264189,0.243235
2,Random Forest,0.768152,0.271375,0.049324,0.083476
0,Logistic Regression,0.785942,0.000000,0.000000,0.000000